export class ProduitdModel {
  id:any;
  Categorie:any;
  SousCategorie:any;
  Brand:any;
  Produit:any;
  QteDsStock:any;
  Prix:any;
  PrixR:any;
  Reduction:any;
  Couleur:any;
  Taille:any;
  Genre:any;
  GroupeAge:any;
  Images:any;
  DetailsP:any;
  PrixLivraision:any;
  livraisonestime:any;
 }
